---
# 
# Execute IBM Installation Manager imcl commands listInstalledPackages -long, listInstalledPackages -verbose and output to files 
# listinstalledpackages_hostname.out, listinstalledpackages_verbose_hostname.out for information on WebSphere, IBM HTTP Server packages installed. 
- import_tasks: was_http_list_installed_packages.yml
  when: ansible_facts['os_family'] == 'AIX' or ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'Suse'
