---
#
# Execute IBM Installation Manager imcl commands listInstalledPackages -long, listInstalledPackages -verbose and output to files
# listinstalledpackages_hostname.out, listinstalledpackages_verbose_hostname.out for information on WebSphere, IBM HTTP Server packages installed.
#
# Create log directory for logs of standard output, error messages
- name: Create {{ log_dir }}/was for logs of standard output, error messages
  file:
    path: "{{ log_dir }}/was"
    state: directory
    mode: '0777'
      #  become: true
      #become_user: root

- name: Copy script was_list_packages.sh to temporary directory
  copy:
    src: files/was_list_packages.sh
    dest: "{{ wasadm_home }}/"
    mode: '0777'

- name: 'Execute IBM Installation Manager imcl commands listInstalledPackages -long, listInstalledPackages -verbose'
  shell: su - wasadm -c '{{ wasadm_home }}/was_list_packages.sh > {{ log_dir }}/was/was_list_packages.out 2>&1'
  register: script
  ignore_errors: True
  changed_when: script.rc == 0
    #become: true
    #become_user: root

- name: Permit access to read log files in {{ log_dir }}/was
  command: chmod -R 777 {{ log_dir }}/was
  args:
    warn: false
  changed_when: false
    #become: true
    #become_user: root

- name: 'Store content of {{ log_dir }}/was/was_list_packages.out in variable output when script was_list_packages.sh fails'
  command: cat {{ log_dir }}/was/was_list_packages.out
  register: output
  when: script.rc != 0

- name: 'Output of {{ log_dir }}/was/was_list_packages.out when script was_list_packages.sh fails'
  debug:
    var: output.stdout_lines
  failed_when: script.rc != 0
  when: script.rc != 0

# Delete script
- name: "Delete file {{ wasadm_home }}/was_list_packages.sh"
  file:
    path: "{{ wasadm_home }}/was_list_packages.sh"
    state: absent
      #become: true
      #become_user: root
