---
# 
# tar, gzip backups of WebSphere, HTTP Server install directory and IBM Installation Manager locations.
- import_tasks: was_backup.yml
  when: ansible_facts['os_family'] == 'AIX' or ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'Suse'
