---
#
# Upgrade WebSphere, HTTP Server on AIX, Linux with Installation Manager imcl install commands for fixpacks and/or interim fixes.
# Also imcl uninstall and rollback commands can be used for backout of change.
#
# Provided stop, start scripts rc.was, rc.http and configuration files rc.was.config, rc.http.config not used from
# /var/lib/awx/projects/project/roles/was_http_stop_start/files.
#
# Perform the following updates if previous local site scripts to stop and start IBM HTTP Server and WebSphere are used.
# - Create Ansible Tower Job Template with Survey using this playbook file was_upgrade2.yml.
# - Update script was_http_stop_start.sh in /var/lib/awx/projects/project/roles/was_http_stop_start/files to execute
# local site stop, start scripts for IBM HTTP Server, WebSphere instead of provided rc.http, rc.was scripts.
# Test updated script was_http_stop_start.sh.
# - Uncomment and specify value for default variable userid in /var/lib/awx/projects/project/roles/was_upgrade/defaults/main.yml
# Also create a Survey prompt for Ansible variable userid in Ansible Tower Job Template for playbook was_upgrade2.yml.
#
# /var/lib/awx/projects/project/roles/was_upgrade/defaults/main.yml contains default variables.
# /var/lib/awx/projects/project/roles/filesystem_freespace/defaults/main.yml contains default variables.
# /var/lib/awx/projects/project/roles/mount_unmount_software_repository_nfs/defaults/main.yml contains default variables.
# /var/lib/awx/projects/project/roles/was_http_stop_start/defaults/main.yml contains default variables.
# /var/lib/awx/projects/project/roles/was_http_logs_check_errors/main.yml defaults contains default variables.
# These default variables can be changed or overridden with job template survey.
#
#
- hosts: all
  become: true
  become_exe: pbrun
  become_flags: ''
  vars: 
    wasadm_home: '/users/wasadm'
  strategy: free
  tasks:
#
# Validate variable path_search does not contain /
  - name: Validate variable path_search does not contain /
    fail:
      msg: 'Variable path_search value {{ path_search }} contains a / which is not allowed'
    when: path_search.find('/') != -1

#
# Check free space in MB for filesystem
# Role filesystem_freespace has default variable fileystem to override with Job Template Survey variable filesystem.
# Role filesystem_freespace has default variable fileystem_freespace_mb to override with Job Template Survey variable filesystem_freespacemb.
  - import_role:
      name: filesystem_freespace

#
# NFS mount the software repository with mountpoint of variable mountpoint with default value of /mnt
  - import_role:
      name: mount_unmount_software_repository_nfs
    vars:
      actionm: 'mount'
    when: nfs_mount == 'yes'

#
# Check if path/file from variable file_cmds exists for input file of Installation Manager imcl install commands
  - name: 'Check if {{ file_cmds }} from variable file_cmds exists for input file of Installation Manager imcl install commands'
    stat:
      path: '{{ file_cmds }}'
    register: file_result

  - name: 'Fail if {{ file_cmds }} from variable file_cmds does not exist'
    fail:
      msg: '{{ file_cmds }} from variable file_cmds does not exist'
    when: not file_result.stat.exists

#
# Stop IBM HTTP Server and WebSphere 
  - import_role:
      name: was_http_stop_start
    vars:
      actionp: 'stop'
    when: action_stop == 'yes'

#
# Upgrade WebSphere, HTTP Server on AIX, Linux with Installation Manager imcl install commands for fixpacks and/or interim fixes
  - import_role:
      name: was_upgrade

#
# Execute Change ownership recursive of /optn/IBM/WebSphere/AppServer to userid:group.
  - name: 'Change ownership recursive of /{{ path_search }}/{{ websphere_install_dir }} to {{ userid }}:{{ group }}'
    file:
      path: '/{{ path_search }}/{{ websphere_install_dir }}'
      owner: '{{ userid }}'
      group: '{{ group }}'
      recurse: yes
        #become: true
        #become_user: root

#
# Remove other permissions recursive of /optn/IBM/WebSphere/AppServer for IBM WebSphere Appplication Server (WAS)
# technical specification spreadsheet Section # AS.1.8.1.4, AS.1.8.1.15, AS.1.8.1.16, AS.1.8.1.17, AS.1.8.1.18,
# AS.1.8.1.19, AS.1.8.1.20, AS.1.8.1.21, AS.1.8.1.22, AS.1.8.1.23, AS.1.8.1.24, AS.1.8.1.25 that is checked by
# GCM WebSphere security configuration scan.
  - name: 'Remove other permissions recursive for /{{ path_search }}/{{ websphere_install_dir }}'
    file:
      path: '/{{ path_search }}/{{ websphere_install_dir }}'
      state: directory
      recurse: yes
      mode: o-rwx
        #become: true
        #become_user: root

#
# Start IBM HTTP Server and WebSphere.
# Variable action_start of yes that WebSphere servers are to be started.
# Variable action_start_was set for individual WebSphere server to be started. Add variable action_start_was: yes to Ansible host. 
# This is defined if some individual servers need to be started later manually.
# Variable action_start_was: yes could also be added to Ansible group of Ansible hosts if group of WebSphere servers to be started.
  - import_role:
      name: was_http_stop_start
    vars:
      actionp: 'start'
    when: action_start == 'yes'
#
# If all WebSphere servers cannot be automatically started, then comment above statement when: action_start == 'yes' and uncomment statement below.
#   when: action_start == 'yes' and action_start_was is defined
#
# Variable action_start_was set for individual WebSphere server to be started. Add variable action_start_was: yes to Ansible host.
# This is defined if some individual servers need to be started later manually.
# Variable action_start_was: yes could also be added to Ansible group of Ansible hosts if group of WebSphere servers to be started.
#
# Execute IBM Installation Manager imcl commands listInstalledPackages -long, listInstalledPackages -verbose and output to files.
# listinstalledpackages_hostname.out, listinstalledpackages_verbose_hostname.out in /tmp/output/was for information on 
# WebSphere, IBM HTTP Server packages installed.
#- import_role:
    #   name: was_http_list_installed_packages

#
# To check for error, warning messages in WebSphere SystemOut.log, SystemError.log files and to check for error, warning messages in 
# IBM HTTP Server error_log_*, http_plugin_log_* log files.
# Review if default variables in /var/lib/awx/projects/project/roles/was_http_logs_check_errors/defaults/main.yml need to be updated.
#- include_role:
      #name: was_http_logs_check_errors
        #    when: action_start == 'yes'
#
# If all WebSphere servers cannot be automatically started, then comment above statement when: action_start == 'yes' and uncomment statement below.
#   when: action_start == 'yes' and action_start_was is defined
#
# Variable action_start_was set for individual WebSphere server to be started. Add variable action_start_was: yes to Ansible host.
# This is defined if some individual servers need to be started later manually.
# Variable action_start_was: yes could also be added to Ansible group of Ansible hosts if group of WebSphere servers to be started.

# NFS unmount the software repository with mountpoint of variable mountpoint with default value of /mnt
  - include_role:
      name: mount_unmount_software_repository_nfs
    vars:
      actionm: 'unmount'
    when: nfs_unmount == 'yes'
