---
# 
# NFS mount the software repository with mountpoint of variable mountpoint if AIX or Linux
- import_tasks: mount_nfs.yml
  when: ansible_facts['os_family'] == 'AIX' or ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'Suse'
