---
#
# Check syntax of file /etc/rc.was.config.
# Check number of entries for 2nd field userid in /etc/rc.was.config against number of java processes for same userid. 
- import_tasks: was_syntax_processes_check.yml
  when: ansible_facts['os_family'] == 'AIX' or ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'Suse'
