---
#
# Upgrade WebSphere, HTTP Server on AIX, Linux with Installation Manager imcl install commands for fixpacks and/or interim fixes 
- import_tasks: was_upgrade.yml
  when: ansible_facts['os_family'] == 'AIX' or ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'Suse'
